# Generated by Django 4.0.6 on 2022-07-09 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('sobrenome', models.CharField(default='', max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=14)),
                ('cpf', models.CharField(max_length=11, null=True, unique=True)),
                ('cnpj', models.CharField(max_length=14, null=True)),
                ('tipo', models.CharField(choices=[('PF', 'Fisica'), ('PJ', 'Juridica')], max_length=2)),
                ('genero', models.CharField(choices=[('PF', 'Feminino'), ('PJ', 'Masculino')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('conta', models.PositiveIntegerField(default=46092, editable=False, primary_key=True, serialize=False)),
                ('saldo', models.FloatField(default=0)),
                ('tipo', models.CharField(choices=[('S', 'Salário'), ('C', 'Corrente'), ('P', 'Poupança')], default='Corrente', max_length=8)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.cliente')),
            ],
        ),
    ]
