# Generated by Django 4.0.6 on 2022-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=32282, editable=False, primary_key=True, serialize=False),
        ),
    ]
