# Generated by Django 4.0.6 on 2022-07-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='conta',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='numero_conta',
            field=models.PositiveIntegerField(default=55233, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
