# Generated by Django 4.0.6 on 2022-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_remove_contabancaria_conta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contabancaria',
            name='numero_conta',
        ),
        migrations.AddField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=42756, editable=False, primary_key=True, serialize=False),
        ),
    ]
