# Generated by Django 4.0.6 on 2022-07-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0005_remove_contabancaria_numero_conta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=40665, editable=False, primary_key=True, serialize=False),
        ),
    ]
