# Generated by Django 4.0.6 on 2022-07-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contabancaria',
            old_name='cliente',
            new_name='titular',
        ),
        migrations.RemoveField(
            model_name='contabancaria',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=43099, editable=False, primary_key=True, serialize=False),
        ),
    ]
