# Generated by Django 4.0.6 on 2022-07-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=69796, editable=False, primary_key=True, serialize=False),
        ),
    ]
