# Generated by Django 4.0.6 on 2022-07-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contabancaria',
            name='tipo',
            field=models.CharField(choices=[('S', 'Salário'), ('C', 'Corrente'), ('P', 'Poupança')], default='Corrente', max_length=8),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=43536, editable=False, primary_key=True, serialize=False),
        ),
    ]
