# Generated by Django 4.0.6 on 2022-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_contabancaria_tipo_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=16114, editable=False, primary_key=True, serialize=False),
        ),
    ]
