# Generated by Django 4.0.6 on 2022-07-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0013_alter_cliente_telefone_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=2),
        ),
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=93024, editable=False, primary_key=True, serialize=False),
        ),
    ]
