# Generated by Django 4.0.6 on 2022-07-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0014_alter_cliente_genero_alter_contabancaria_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contabancaria',
            name='conta',
            field=models.PositiveIntegerField(default=47019, editable=False, primary_key=True, serialize=False),
        ),
    ]
