# Generated by Django 4.0.6 on 2022-07-09 20:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('Transfer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario', models.IntegerField()),
                ('remetente', models.IntegerField()),
                ('tipo', models.CharField(choices=[('t', 'tranferencia'), ('r', 'recebimento')], default='transferencia', max_length=13)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contas.contabancaria')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
