# Generated by Django 4.0.6 on 2022-07-09 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_contabancaria_conta'),
        ('operacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.contabancaria'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('d', 'deposito'), ('s', 'saque')], default='deposito', max_length=10),
        ),
    ]
