# Generated by Django 4.0.6 on 2022-07-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0002_movimentacao_conta_movimentacao_quantidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='destinatario',
            new_name='beneficiario',
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('deposito', 'deposito'), ('saque', 'saque')], default='deposito', max_length=10),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'tranferencia'), ('recebimento', 'recebimento')], default='transferencia', max_length=13),
        ),
    ]
