# Generated by Django 4.0.6 on 2022-07-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_rename_destinatario_transferencia_beneficiario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
