# Generated by Django 4.0.6 on 2022-07-10 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0004_movimentacao_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'verbose_name_plural': 'Movimentações'},
        ),
    ]
