# Generated by Django 4.0.6 on 2022-07-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0005_alter_movimentacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['data'], 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('D', 'deposito'), ('S', 'saque')], default='deposito', max_length=10),
        ),
    ]
