# Generated by Django 4.0.6 on 2022-07-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_alter_contabancaria_conta'),
        ('operacoes', '0006_alter_movimentacao_options_alter_movimentacao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='remetente',
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.contabancaria'),
        ),
    ]
