# Generated by Django 4.0.6 on 2022-07-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0007_remove_transferencia_remetente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(default='enviada', max_length=13),
        ),
    ]
