# Generated by Django 4.0.6 on 2022-07-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0008_alter_transferencia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
