# Generated by Django 4.0.6 on 2022-07-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0009_alter_transferencia_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='tipo',
        ),
    ]
