# Generated by Django 4.0.6 on 2022-07-18 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0010_remove_transferencia_tipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movimentacao',
        ),
    ]
